# Generated by Django 6.0.5 on 2026-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inference_mode',
            field=models.CharField(choices=[('full', 'Full Pipeline (LLM + Rules + Keyword)'), ('rule_only', 'Rules + Keyword Only (No LLM)')], default='full', help_text="'full' runs all 4 pipeline stages including LLM. 'rule_only' skips Stage 1b (Llama Guard) and Stage 2 (clinical LLM) — only rule engine + keyword filter run. Lower cost, better privacy for FERPA-strict institutions.", max_length=20),
        ),
    ]
