# Generated by Django 5.1.6 on 2025-03-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('student_email', models.EmailField(max_length=250)),
                ('university_id', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('student_name', 'student_email')},
            },
        ),
    ]
