services:
  db:
    image: mysql:8
    container_name: my-mysql-container
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: ${DOCKER_USERNAME:-local}/django-app:latest
    container_name: django-app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - IS_DOCKER_DEV=true  # This ensures DEBUG=True in local containers
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    command: bash -c "python manage.py makemigrations surveys && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    # command: >
    #   bash -c "
    #   echo '===== Starting commands =====' &&
    #   ls -la /frontend/static/ &&
    #   echo '===== Running collectstatic =====' &&
    #   python manage.py collectstatic --noinput --verbosity 3 &&
    #   echo '===== Checking staticfiles =====' &&
    #   ls -la /app/staticfiles/ &&
    #   echo '===== Starting server =====' &&
    #   python manage.py runserver 0.0.0.0:8000
    #   "
volumes:
  mysql_data:
