# Use an official Python image as base
FROM python:3.12

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .

# Install PostgreSQL client
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && apt-get clean \
    && pip install --no-cache-dir -r requirements.txt

# No need to copy files as we'll mount them as a volume

# Expose the port that Django runs on
EXPOSE 8000

# Set the default command to run Django
CMD ["bash", "-c", "python manage.py makemigrations surveys chat && python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 core.asgi:application"]