services:
  db:
    image: mysql:8
    container_name: my-mysql-container
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ${DOCKER_USERNAME}/django-app:latest
    container_name: django-app
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    ports:
      - "8000:8000"

volumes:
  mysql_data: