# Generated by Django 5.1.7 on 2025-03-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='university_id',
            field=models.CharField(default='Unknown', max_length=250),
        ),
    ]
