# Generated by Django 5.2 on 2025-05-09 02:23

import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedstudents',
            name='school_email',
            field=models.EmailField(max_length=250, validators=[surveys.models.validate_edu_email]),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_email',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False, validators=[surveys.models.validate_edu_email]),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='school_email',
            field=models.EmailField(max_length=250, validators=[surveys.models.validate_edu_email]),
        ),
    ]
