# Generated by Django 6.0.5 on 2026-05-17 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisAssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('primary_concern', models.CharField(blank=True, max_length=50)),
                ('counselor_brief', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence_phrases', models.JSONField(default=list)),
                ('keyword_matches', models.JSONField(default=list)),
                ('classifier_flagged', models.BooleanField(default=False)),
                ('classifier_categories', models.JSONField(default=list)),
                ('provider', models.CharField(blank=True, help_text="LLM provider (e.g. 'anthropic/claude-haiku-4-5'). Empty if no Stage 2.", max_length=50)),
                ('degraded_mode', models.BooleanField(default=False)),
                ('degraded_reason', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FlaggingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rule_type', models.CharField(choices=[('any_question', 'Any Question'), ('sum', 'Sum'), ('average', 'Average')], max_length=20)),
                ('threshold', models.FloatField()),
                ('comparison', models.CharField(choices=[('gte', '>='), ('lte', '<=')], max_length=3)),
                ('severity', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('severity_order', models.IntegerField(db_index=True, default=0, help_text='Integer magnitude of severity (0=none, 1=low, 2=medium, 3=high). Auto-synced from severity in save() using SEVERITY_ORDER from moderation/schemas.py. Used for DB-level ordering since string ordering on enum names is alphabetic, not magnitude.')),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity_order', 'category'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='final_severity',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='none', help_text='Maximum severity across all pipeline stages (rule engine + per-question assessments).', max_length=10),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='final_severity_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Integer magnitude of final_severity (0=none, 1=low, 2=medium, 3=high). Auto-synced from final_severity in save() using SEVERITY_ORDER from moderation/schemas.py. Used for DB-level ordering since string ordering on enum names is alphabetic.'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='inference_mode_used',
            field=models.CharField(blank=True, choices=[('full', 'Full'), ('rule_only', 'Rule Only')], help_text='Inference mode actually used when this survey was processed. Snapshot at submission time. Persists for audit even if Institution.inference_mode changes later.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='pipeline_latency_ms',
            field=models.IntegerField(blank=True, help_text='Total pipeline execution time in ms. NULL until Celery task completes.', null=True),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['flagged', '-final_severity_order', '-created'], name='surveys_sur_flagged_22c942_idx'),
        ),
        migrations.AddField(
            model_name='crisisassessmentrecord',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='crisisassessmentrecord',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_assessments', to='surveys.surveyresponse'),
        ),
        migrations.AddIndex(
            model_name='flaggingrule',
            index=models.Index(fields=['category', 'enabled'], name='surveys_fla_categor_8495cb_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggingrule',
            index=models.Index(fields=['enabled'], name='surveys_fla_enabled_653a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisassessmentrecord',
            index=models.Index(fields=['survey_response'], name='surveys_cri_survey__04ac4a_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisassessmentrecord',
            index=models.Index(fields=['severity', 'created'], name='surveys_cri_severit_7c54f0_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisassessmentrecord',
            index=models.Index(fields=['degraded_mode'], name='surveys_cri_degrade_7804b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='crisisassessmentrecord',
            constraint=models.UniqueConstraint(fields=('survey_response', 'question'), name='unique_assessment_per_question'),
        ),
    ]
