# Generated by Django 5.2.1 on 2025-05-22 02:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.institution')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('likert', 'Likert Scale (1-5)'), ('text', 'Text Response')], default='likert', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveytemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveytemplate'),
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='q5',
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likert_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('text_response', models.TextField(blank=True, null=True)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.surveyresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion')),
            ],
            options={
                'unique_together': {('survey_response', 'question')},
            },
        ),
    ]
