# Generated by Django 5.1.7 on 2025-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresponse_university_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=250)),
                ('student_email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('university_id', models.CharField(max_length=250)),
            ],
        ),
    ]
