# Generated by Django 6.0.5 on 2026-05-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_crisisassessmentrecord_flaggingrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisassessmentrecord',
            name='provider',
            field=models.CharField(blank=True, help_text="LLM provider (e.g. 'anthropic/claude-sonnet-4-6'). Empty if no Stage 2.", max_length=50),
        ),
    ]
