# Generated by Django 5.1.6 on 2025-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresponse_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='schoolEmail',
            new_name='school_email',
        ),
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='studentName',
            new_name='student_name',
        ),
    ]
