# Generated by Django 5.2.1 on 2025-05-24 07:46

import django.core.validators
import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_surveyresponse_unique_together_surveytemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveytemplate',
            name='created',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), surveys.models.validate_edu_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
