# Generated by Django 5.1.7 on 2025-03-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='school_email',
        ),
    ]
