# Generated by Django 5.2.1 on 2025-05-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_surveytemplate_created_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('general', 'General Question'), ('sleep', 'Sleep Quality'), ('stress', 'Stress Level'), ('support', 'Support Perception')], default='general', max_length=20),
        ),
    ]
