# Generated by Django 5.1.6 on 2025-02-10 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_schoolemail_surveyresponse_school_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=250)),
                ('student_name', models.CharField(max_length=250)),
                ('student_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyresponse')),
            ],
        ),
    ]
