# Generated by Django 5.2.1 on 2025-05-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveyquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_choices',
            field=models.JSONField(blank=True, help_text='Custom answer choices for Likert scale questions', null=True),
        ),
    ]
