# Generated by Django 5.1.6 on 2025-02-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_flaggedstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flaggedstudents',
            old_name='student_email',
            new_name='school_email',
        ),
    ]
