# Generated by Django 5.1.6 on 2025-02-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0005_rename_student_email_flaggedstudents_school_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flaggedstudents",
            unique_together={("student_response",)},
        ),
        migrations.AlterUniqueTogether(
            name="surveyresponse",
            unique_together={("student_name", "school_email")},
        ),
    ]
