# Generated by Django 5.2.1 on 2025-05-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveyquestion_answer_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveytemplate',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
