# Generated by Django 5.1.6 on 2025-03-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_flaggedstudents_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='university_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
