# Generated by Django 6.0.2 on 2026-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_surveyresponse_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_institution_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('institution_admin', 'Institution Admin'), ('counselor', 'Counselor'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
