CREATE USER IF NOT EXISTS 'health_user'@'localhost' IDENTIFIED BY '$MYSQL_HEALTH_USER_PASSWORD';
CREATE USER IF NOT EXISTS 'health_user'@'%' IDENTIFIED BY '$MYSQL_HEALTH_USER_PASSWORD';
GRANT SELECT ON *.* TO 'health_user'@'localhost';
GRANT SELECT ON *.* TO 'health_user'@'%';
FLUSH PRIVILEGES;
