# Generated by Django 5.1.6 on 2025-02-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_surveyresult_question1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyresult",
            old_name="question1",
            new_name="q1",
        ),
        migrations.RenameField(
            model_name="surveyresult",
            old_name="question2",
            new_name="q2",
        ),
        migrations.RenameField(
            model_name="surveyresult",
            old_name="question3",
            new_name="q3",
        ),
        migrations.RenameField(
            model_name="surveyresult",
            old_name="question4",
            new_name="q4",
        ),
        migrations.RenameField(
            model_name="surveyresult",
            old_name="question5",
            new_name="q5",
        ),
    ]
