# Generated by Django 5.1.6 on 2025-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_question1_surveyresult_q1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresult",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="surveyresult",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="surveyresult",
            unique_together={("name", "email")},
        ),
    ]
