# Generated by Django 5.1.6 on 2025-02-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_surveyresult_submitted_at_alter_surveyresult_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresult",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
