name: Deploy to AWS EC2

on:
  push:
    branches:
      - ziyue_branch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github_actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug - List files in repository
      run: |
        pwd
        ls -la
        find . -name "Dockerfile" -type f

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        context: .
        file: ./Dockerfile  # Specify the path to your Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: github_actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy docker-compose file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.yaml"
        target: "~/app"

    - name: Create .env file on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/app
          cat > ~/app/.env << EOL
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          EOL
          
          # Verify the file was created
          ls -la ~/app/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 进入应用目录
          cd ~/app
          
          # 停止现有容器
          docker-compose down || true
          
          # 拉取最新镜像
          docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          
          # 启动所有服务
          docker-compose up -d

    - name: Debug - Check secrets
      run: |
        echo "MYSQL_DATABASE is defined: ${{ secrets.MYSQL_DATABASE != '' }}"
        echo "MYSQL_USER is defined: ${{ secrets.MYSQL_USER != '' }}"
        echo "MYSQL_PASSWORD is defined: ${{ secrets.MYSQL_PASSWORD != '' }}"
        echo "MYSQL_ROOT_PASSWORD is defined: ${{ secrets.MYSQL_ROOT_PASSWORD != '' }}"
        echo "MYSQL_HOST is defined: ${{ secrets.MYSQL_HOST != '' }}"
        echo "MYSQL_PORT is defined: ${{ secrets.MYSQL_PORT != '' }}"
        echo "DOCKER_USERNAME is defined: ${{ secrets.DOCKER_USERNAME != '' }}"