name: Deploy to AWS EC2

on:
  push:
    branches:
      - ziyue_branch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github_actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/django-app:latest
        context: .
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: github_actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy docker-compose file /Dockerfile to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.prod.yaml, Dockerfile"
        target: "~/app"

    - name: Create .env file on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/app
          cat > ~/app/.env << EOL
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          EOL

    - name: Configure Docker Mirror
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo mkdir -p /etc/docker
          echo '{
            "registry-mirrors": [
              "https://docker.1ms.run",
              "https://docker.xuanyuan.me"
            ]
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          
          # Debug: Check directory contents
          echo "Directory contents:"
          ls -la
          
          # Debug: Check Docker images before pull
          echo "Docker images before pull:"
          docker images
          
          # Pull image with verbose output
          echo "Pulling Docker image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          
          # Debug: Verify image was pulled
          echo "Docker images after pull:"
          docker images | grep django-app
          
          # Debug: Check image details
          echo "Image details:"
          docker inspect ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          
          # Continue with deployment
          docker-compose -f docker-compose.prod.yaml up -d
          
          # Debug: Check running containers
          echo "Running containers:"
          docker ps
          
          # Debug: Check container logs
          echo "Container logs:"
          docker-compose -f docker-compose.prod.yaml logs web
