name: Deploy to AWS EC2

on:
  push:
    branches:
      - ziyue_branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github_actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare EC2 directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/app
            mkdir -p ~/app
            chmod -R 755 ~/app

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."  # Copies everything (respects .gitignore/.dockerignore)
          target: "~/app"
          strip_components: 1

      - name: Create .env file on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > ~/app/.env << EOL
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOL
            ls -la ~/app/

      - name: Build and run with Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            docker-compose -f docker-compose.prod.yaml down
            docker system prune -f
            docker-compose -f docker-compose.prod.yaml up --build -d
            docker-compose -f docker-compose.prod.yaml logs web
